import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    kpis: [
      {
        id: 1,
        icon: "Megaphone",
        color: "#2563EB",
        label: "Campaign Conducted",
        value: "12",
        sub: "+2",
        subcolor: "#22C55E",
        sub2: "this month",
        subcolor2: "#6B7280",
      },
      {
        id: 2,
        icon: "Users",
        color: "#10B981",
        label: "Outreach Reach",
        value: "650,000",
        sub: "+10%",
        subcolor: "#22C55E",
        sub2: "vs last month",
        subcolor2: "#6B7280",
      },
      {
        id: 3,
        icon: "FileText",
        color: "#F59E0B",
        label: "Applications Received",
        value: "890",
        unit: "",
        sub: "+15%",
        subcolor: "#22C55E",
        sub2: "vs last month",
        subcolor2: "#6B7280",
      },
      {
        id: 4,
        icon: "ArrowRightLeft",
        color: "#7C3AED",
        label: "Conversion Rate",
        value: "1.37%",
        unit: "",
        sub: "+0.2%",
        subcolor: "#22C55E",
        sub2: "this month",
        subcolor2: "#6B7280",
      },
      {
        id: 5,
        icon: "BadgeCheck",
        color: "#D946EF",
        label: "Approved Applications",
        value: "15",
        unit: "",
        sub: "+2",
        subcolor: "#22C55E",
        sub2: "this month",
        subcolor2: "#6B7280",
      },
      {
        id: 6,
        icon: "TrendingDown",
        color: "#DC2626",
        label: "Drop-off Rate",
        value: "85%",
        unit: "",
        sub: "-5%",
        subcolor: "#DC2626",
        sub2: "this month",
        subcolor2: "#6B7280",
      },
    ],
    activities: [
      {
        id: 1,
        icon: "CheckCircle",
        iconColor: "#2563EB",
        textcolor: "#2563EB",
        bgColor: "#DBEAFE",
        text: 'Campaign "Back to School Drive" completed',
        sub: "Reach: 125,000",
        unit: "2h ago",
      },
      {
        id: 2,
        icon: "Handshake",
        iconColor: "#059669",
        textcolor: "#059669",
        bgColor: "#D1FAE5",
        text: "New partnership with Greenfield Foundation",
        sub: "Potential reach: 50,000+",
        unit: "1d ago",
      },
      {
        id: 3,
        icon: "TrendingUp",
        iconColor: "#D97706",
        textcolor: "#D97706",
        bgColor: "#FEF3C7",
        text: "Application spike detected",
        sub: "+120 applications in the last 24h",
        unit: "2d ago",
      },
      {
        id: 4,
        icon: "Calendar",
        iconColor: "#7C3AED",

        bgColor: "#EDE9FE",
        text: "Upcoming event: Youth Awareness Campaign",
        sub: "Date: May 28, 2024",
        unit: "5d ago",
      },
    ],
  });
}
